theme: jekyll-theme-minimal
title: Crypto Backed Stablecoin 
description: An open source, proof of work masternode-based stablecoin
avatar: "bitcoin.png"
title-img: "bitcoin.png"

navbar-links:
  Ecosystem: "https://cryptoslate.com/cryptos/stablecoin/"
  Comunity: "https://twitter.com/BalancedSoft"
  Vote: "https://www.btcsquare.net/vote"

social-network-links:
  email: "inquery@softbalanced.com"
  facebook: softbalanced
  github: softbalanced
  twitter: softbalanced
  youtube: c/softbalanced
