theme: jekyll-theme-minimal
title: Crypto Backed Stablecoin USBL
description: An open source, 1:1 pegged, fixed rate 
avatar: "bitcoin.png"
title-img: "bitcoin.png"

navbar-links:
  Ecosystem: "https://dexstats.info/"
  Comunity: "https://discord.com/invite/HkHyKCjfRQ"
  Vote: "https://nomics.com/assets/usbl-balanced-dollar/markets"

social-network-links:
  email: "inquery@softbalanced.com"
  facebook: softbalanced
  github: softbalanced
  twitter: softbalanced
  youtube: c/softbalanced
